### ISSUE TITLE
COMMENT_FILE_WRITTEN always false

### ISSUE THREAD

**Issue by jirikralik** [py-cov-action/python-coverage-comment-action#291]
Hello guys, 
could you please explain me this flag? When it is true? I followed your approach and we are able to generate comments with % coverage for our PRs, however I am not able to update the "python-coverage-comment-action-data" branch. The branch was generated, but now for my PRs, the flag is always false, and it wont store the comment. Thank you for your help!
![Screenshot from 2023-10-23 15-18-28](https://github.com/py-cov-action/python-coverage-comment-action/assets/45180484/49b2358f-4df1-4262-90b1-1def9aff8680)

**Comment by kieferro** [comment]
The `COMMENT_FILE_WRITTEN` flag indicates whether the action was able to post the comment when it was first called.
If you look at the workflow example [here](https://github.com/py-cov-action/python-coverage-comment-action#basic-usage), you can see that the action is called once and if it wasn't able to post the comment (because the PR is external and therefore doesn't have the necessary permissions) it uploads the comment and posts it from a separate workflow with more permissions.
But if you only use PRs from contributors with permission, that flag is always false. (In that case you could also just use the workflow structure described [here](https://github.com/py-cov-action/python-coverage-comment-action#basic-usage-without-external-contributors) and completely ignore the flag).


> however I am not able to update the "python-coverage-comment-action-data" branch

This is only supposed to happen after a push event on the default branch. If I understand you correctly, you are talking about a PR event. What would be the behaviour you would expect?

**Comment by ewjoachim** [comment]
(... Maybe we need to be clearer in the Readme. It's always a struggle between adding more content to cover more cases, and removing content because nobody reads when it's too long).

**Comment by jirikralik** [comment]
thank you guys. I adjusted the script and now it is working!

**Comment by jirikralik** [comment]
Job done!
