### ISSUE TITLE
Detailed statistics on the coverage data branch

### ISSUE THREAD

**Issue by kieferro** [py-cov-action/python-coverage-comment-action#82]
It would be nice to use the coverage data branch not only for storing the data, but also to display other stats there.
For example, the HTML reports generated by pycoverage could be used for this.

**Comment by ewjoachim** [comment]
We may need to use https://htmlpreview.github.io/ because we probably won't be able to serve arbitrary html in GitHub.

The alternative is if we manage to have all the reports in markdown format, though I don't think it will let us display code in a readable way (with line numbers, line colors for coverage status etc)
